
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rheo
 */
public class Maininterface extends javax.swing.JFrame {
    private Object jTextfield1;

    /**
     * Creates new form Maininterface
     */
    public Maininterface() {
        initComponents();
        jTextArea1.setText("Vul uw beginstand, eindstand en fase in");
        jTextField1.setBackground(Color.GREEN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBeginstand = new javax.swing.JTextField();
        txtEindstand = new javax.swing.JTextField();
        lblBeginstand = new javax.swing.JLabel();
        lblEindstand = new javax.swing.JLabel();
        btnBereken = new javax.swing.JButton();
        txtVerbruik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbFase = new javax.swing.JComboBox();
        txtFasebedrag = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBedragA = new javax.swing.JTextField();
        txtBedragB = new javax.swing.JTextField();
        txtBedragC = new javax.swing.JTextField();
        txtBedragD = new javax.swing.JTextField();
        txtBedragE = new javax.swing.JTextField();
        txtBedragF = new javax.swing.JTextField();
        txtBedragG = new javax.swing.JTextField();
        lblBedragA = new javax.swing.JLabel();
        lblBedragB = new javax.swing.JLabel();
        lblBedragC = new javax.swing.JLabel();
        lblBedragD = new javax.swing.JLabel();
        lblBedragE = new javax.swing.JLabel();
        lblBedragF = new javax.swing.JLabel();
        lblBedragG = new javax.swing.JLabel();
        lblStandstatus = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        txtBerekeningA = new javax.swing.JTextField();
        txtBerekeningB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBerekeningC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBerekeningD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBerekeningE = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBerekeningF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBerekeningG = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        txtTotaal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtBeginstand.setName("txtBeginstand"); // NOI18N

        txtEindstand.setName("txtEindstand"); // NOI18N
        txtEindstand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEindstandActionPerformed(evt);
            }
        });

        lblBeginstand.setText("Beginstand");
        lblBeginstand.setName("lblBeginstand"); // NOI18N

        lblEindstand.setText("Eindstand");
        lblEindstand.setName("lblEindstand"); // NOI18N

        btnBereken.setText("Bereken");
        btnBereken.setName("btnBereken"); // NOI18N
        btnBereken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerekenActionPerformed(evt);
            }
        });

        txtVerbruik.setEditable(false);
        txtVerbruik.setName("txtVerbruik"); // NOI18N

        jLabel3.setText("Verbruik");
        jLabel3.setName(""); // NOI18N

        cmbFase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kies een fase", "Fase 1", "Fase 2", "Fase 3" }));
        cmbFase.setName("cmbFase"); // NOI18N
        cmbFase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFaseActionPerformed(evt);
            }
        });

        txtFasebedrag.setEditable(false);
        txtFasebedrag.setName("txtFasebedrag"); // NOI18N

        jLabel1.setText("abonnements kosten");

        jLabel2.setText("Fase");

        txtBedragA.setEditable(false);
        txtBedragA.setName("txtBedragA"); // NOI18N
        txtBedragA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBedragAActionPerformed(evt);
            }
        });

        txtBedragB.setEditable(false);
        txtBedragB.setName("txtBegdragB"); // NOI18N

        txtBedragC.setEditable(false);
        txtBedragC.setName("txtBedragC"); // NOI18N

        txtBedragD.setEditable(false);
        txtBedragD.setName("txtBedragD"); // NOI18N

        txtBedragE.setEditable(false);
        txtBedragE.setName("txtBedragE"); // NOI18N

        txtBedragF.setEditable(false);
        txtBedragF.setName("txtBedragF"); // NOI18N

        txtBedragG.setEditable(false);
        txtBedragG.setName("txtBedragG"); // NOI18N

        lblBedragA.setText("X SRD 0.15");
        lblBedragA.setName("lblBedragA"); // NOI18N

        lblBedragB.setText("X SRD 0.27");
        lblBedragB.setName("lblBedragB"); // NOI18N

        lblBedragC.setText("X SRD 0.30");
        lblBedragC.setName("lblBedragC"); // NOI18N

        lblBedragD.setText("X SRD 0.33");
        lblBedragD.setName("lblBedragD"); // NOI18N

        lblBedragE.setText("X SRD 0.36");
        lblBedragE.setName("lblBedragE"); // NOI18N

        lblBedragF.setText("X SRD 0.37");
        lblBedragF.setName("lblBedragF"); // NOI18N

        lblBedragG.setText("X SRD 0.40");
        lblBedragG.setName("lblBedragG"); // NOI18N

        lblStandstatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblStandstatus.setForeground(new java.awt.Color(255, 0, 0));

        btnReset.setText("Reset");
        btnReset.setName("btnReset"); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtBerekeningA.setEditable(false);
        txtBerekeningA.setName("txtBerekeningA"); // NOI18N

        txtBerekeningB.setEditable(false);
        txtBerekeningB.setName("txtBerekeningB"); // NOI18N

        jLabel4.setText("SRD");

        jLabel5.setText("SRD");

        txtBerekeningC.setEditable(false);
        txtBerekeningC.setName("txtBerekeningC"); // NOI18N

        jLabel6.setText("SRD");

        txtBerekeningD.setEditable(false);
        txtBerekeningD.setName("txtBerekeningD"); // NOI18N

        jLabel7.setText("SRD");

        txtBerekeningE.setEditable(false);
        txtBerekeningE.setName("txtBerekeningE"); // NOI18N

        jLabel8.setText("SRD");

        txtBerekeningF.setEditable(false);
        txtBerekeningF.setName("txtBerekeningF"); // NOI18N

        jLabel9.setText("SRD");

        txtBerekeningG.setEditable(false);
        txtBerekeningG.setName("txtBerekeningG"); // NOI18N

        jLabel10.setText("SRD");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(102, 255, 102));

        txtTotaal.setEditable(false);
        txtTotaal.setName("txtTotaal"); // NOI18N

        jLabel11.setText("Totaal bedrag");

        jLabel12.setText("SRD");

        jLabel13.setText("SRD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBeginstand, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBeginstand, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEindstand, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtEindstand, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtVerbruik, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(cmbFase, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblBedragA, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(113, 113, 113)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtBerekeningB, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtBerekeningA, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtBerekeningC, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtBerekeningD, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtBerekeningE, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtBerekeningF, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtBerekeningG, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(89, 89, 89)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnBereken, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(txtBedragA, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBedragB, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblBedragB, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBedragC, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblBedragC, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBedragD, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblBedragD, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBedragE, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblBedragE, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBedragF, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblBedragF, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBedragG, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblBedragG, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblStandstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(67, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotaal)
                            .addComponent(txtFasebedrag, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                        .addGap(287, 287, 287))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblBeginstand, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEindstand, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBeginstand, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEindstand, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVerbruik, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBereken, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbFase, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lblStandstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtBedragA, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblBedragA))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtBerekeningA, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBedragB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBedragB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtBerekeningB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBedragC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBedragC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtBerekeningC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBedragD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBedragD)
                                    .addComponent(txtBerekeningD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBedragE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBedragE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtBerekeningE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBedragF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBedragF)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtBerekeningF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBedragG, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBedragG)
                                    .addComponent(txtBerekeningG, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jScrollPane1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFasebedrag, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(txtTotaal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEindstandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEindstandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEindstandActionPerformed

    private void btnBerekenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerekenActionPerformed
        // TODO add your handling code here:
       
        
        
   
       

//Assign 'txtVerbruik variable' in pulic variable

//Staaf => Volle verbruik
double Fase = 0 ;
double Beginstand;
double Eindstand;
double Verbruik;
double Totaalverbruik = 0;
double Dremple = 150 ;

double staaf1 = 40.50;
double staaf2 = 45;
double staaf3 = 49.50;
double staaf4 = 54;
double staaf5 = 74;



//Max use of Tier

float Dremple1 = 300;
float Dremple2 = 450;
float Dremple3 = 600;
float Dremple4 = 800;

switch ( cmbFase.getSelectedIndex()) {
    case 1:
        Fase= 10.85;
        break;
    case 2:
        Fase= 16.50;
                break;
        
    case 3:
        Fase = 18.25;
        break;
        
    }
this.txtFasebedrag.setText(String.valueOf (Fase));

Beginstand=Integer.parseInt(this.txtBeginstand.getText());
Eindstand=Integer.parseInt(this.txtEindstand.getText());

Verbruik= Eindstand - Beginstand;
this.txtVerbruik.setText(String.valueOf(Verbruik));




 
       this.txtVerbruik.setText(String.valueOf(Verbruik));
        if (Eindstand < Beginstand){
            this.lblStandstatus.setText("Eindstand Moet Groter zijn dan beginstand, druk op reset en probeer het opnieuw");
             this.txtBeginstand.setText("");
        this.txtEindstand.setText("");
        this.txtVerbruik.setText("");
        this.lblStandstatus.setText("");
        this.txtBedragA.setText("");
        this.txtBerekeningA.setText("");
        this.txtBedragB.setText("");
        this.txtBerekeningB.setText("");
        this.txtBedragC.setText("");
        this.txtBerekeningC.setText("");
        this.txtBedragD.setText("");
        this.txtBerekeningD.setText("");
        this.txtBedragE.setText("");
        this.txtBerekeningE.setText("");
        this.txtBedragF.setText("");
        this.txtBerekeningF.setText("");
        this.txtBedragG.setText("");
        this.txtBerekeningG.setText("");  
        this.txtFasebedrag.setText("");
        this.txtTotaal.setText("");
        this.jTextArea1.setText("Eindstand moet groter zijn dan beginstand");
        
             }
        else this.lblStandstatus.setText("");  
           
     
      jTextField1.setBackground(Color.RED); 
      
      if (Verbruik <= 150) {
          this.txtBedragA.setText(String.valueOf(Verbruik));
          double BedragA = Verbruik * 0.15;
          this.txtBerekeningA.setText(String.valueOf(BedragA));
          Totaalverbruik = BedragA;
          this.txtTotaal.setText(String.valueOf(Totaalverbruik + Fase));
          if (cmbFase.getSelectedIndex() == 0)    
              this.jTextArea1.setText("Vul een Fase in");
          
      }
    else  if (Verbruik <= 300) {
          this.txtBedragB.setText(String.valueOf(Dremple));
          double BedragB = Dremple * 0.27;
          this.txtBerekeningB.setText(String.valueOf(BedragB));
          double BedragC= (Verbruik - Dremple) * 0.30;
         
          this.txtBedragC.setText(String.valueOf(Verbruik-Dremple)); 
          this.txtBerekeningC.setText(String.valueOf(BedragC));
       Totaalverbruik = BedragB + BedragC;
       this.txtTotaal.setText(String.valueOf(Totaalverbruik + Fase));
       if (cmbFase.getSelectedIndex() == 0)    
              this.jTextArea1.setText("Vul een Fase in");
    }
      else  if (Verbruik <= 450) {
          this.txtBedragB.setText(String.valueOf(Dremple));
          double BedragB = Dremple * 0.27;
          this.txtBerekeningB.setText(String.valueOf(BedragB));
          double BedragC= staaf2;
         this.txtBedragC.setText(String.valueOf(Dremple)); 
          this.txtBerekeningC.setText(String.valueOf(BedragC));
          
            double BedragD= (Verbruik - Dremple1) * 0.33;
         this.txtBedragD.setText(String.valueOf(Verbruik - Dremple1)); 
          this.txtBerekeningD.setText(String.valueOf(BedragD));
         Totaalverbruik = BedragB + BedragC + BedragD;
       this.txtTotaal.setText(String.valueOf(Totaalverbruik + Fase)); 
       if (cmbFase.getSelectedIndex() == 0)    
              this.jTextArea1.setText("Vul een Fase in");
    }
       else  if (Verbruik <= 600) {
          this.txtBedragB.setText(String.valueOf(Dremple));
          double BedragB = Dremple * 0.27;
          this.txtBerekeningB.setText(String.valueOf(BedragB));
          double BedragC= staaf2 ;
         this.txtBedragC.setText(String.valueOf(Dremple)); 
          this.txtBerekeningC.setText(String.valueOf(BedragC));
          
            double BedragD= staaf3;
         this.txtBedragD.setText(String.valueOf(Dremple)); 
          this.txtBerekeningD.setText(String.valueOf(BedragD));
          double BedragE= (Verbruik - Dremple2) * 0.36;
         this.txtBedragE.setText(String.valueOf(Verbruik - Dremple2)); 
          this.txtBerekeningE.setText(String.valueOf(BedragE));
         Totaalverbruik = BedragB + BedragC + BedragD + BedragE;
       this.txtTotaal.setText(String.valueOf(Totaalverbruik + Fase));  
       if (cmbFase.getSelectedIndex() == 0)    
              this.jTextArea1.setText("Vul een Fase in");
    }
      
          else  if (Verbruik <= 800) {
          this.txtBedragB.setText(String.valueOf(Dremple));
          double BedragB = Dremple * 0.27;
          this.txtBerekeningB.setText(String.valueOf(BedragB));
          double BedragC= staaf2 ;
         this.txtBedragC.setText(String.valueOf(Dremple)); 
          this.txtBerekeningC.setText(String.valueOf(BedragC));
          
            double BedragD= staaf3;
         this.txtBedragD.setText(String.valueOf(Dremple)); 
          this.txtBerekeningD.setText(String.valueOf(BedragD));
          double BedragE= staaf4;
         this.txtBedragE.setText(String.valueOf(Dremple)); 
          this.txtBerekeningE.setText(String.valueOf(BedragE));
          double BedragF= (Verbruik - Dremple3) * 0.37;
         this.txtBedragF.setText(String.valueOf(Verbruik - Dremple3)); 
          this.txtBerekeningF.setText(String.valueOf(BedragF));
          Totaalverbruik = BedragB + BedragC + BedragD + BedragE + BedragF;
       this.txtTotaal.setText(String.valueOf(Totaalverbruik + Fase)); 
       if (cmbFase.getSelectedIndex() == 0)    
              this.jTextArea1.setText("Vul een Fase in");
    } 
                else  if (Verbruik > 800) {
          this.txtBedragB.setText(String.valueOf(Dremple));
          double BedragB = Dremple * 0.27;
          this.txtBerekeningB.setText(String.valueOf(BedragB));
          double BedragC= staaf2 ;
         this.txtBedragC.setText(String.valueOf(Dremple)); 
          this.txtBerekeningC.setText(String.valueOf(BedragC));
          
            double BedragD= staaf3;
         this.txtBedragD.setText(String.valueOf(Dremple)); 
          this.txtBerekeningD.setText(String.valueOf(BedragD));
          double BedragE= staaf4;
         this.txtBedragE.setText(String.valueOf(Dremple)); 
          this.txtBerekeningE.setText(String.valueOf(BedragE));
          double BedragF= staaf5;
         this.txtBedragF.setText(String.valueOf("200")); 
          this.txtBerekeningF.setText(String.valueOf(BedragF));
          double BedragG= (Verbruik - Dremple4 )* 0.40;
         this.txtBedragG.setText(String.valueOf(Verbruik - Dremple4));
         this.txtBerekeningG.setText(String.valueOf(BedragG)); 
          Totaalverbruik = BedragB + BedragC + BedragD + BedragE + BedragF + BedragG;
       this.txtTotaal.setText(String.valueOf(Totaalverbruik + Fase)); 
       if (cmbFase.getSelectedIndex() == 0)    
              this.jTextArea1.setText("Vul een Fase in");
    }
      if (Eindstand < Beginstand){
            this.lblStandstatus.setText("Eindstand Moet Groter zijn dan beginstand, druk op reset en probeer het opnieuw");
             this.txtBeginstand.setText("");
        this.txtEindstand.setText("");
        this.txtVerbruik.setText("");
        this.lblStandstatus.setText("");
        this.txtBedragA.setText("");
        this.txtBerekeningA.setText("");
        this.txtBedragB.setText("");
        this.txtBerekeningB.setText("");
        this.txtBedragC.setText("");
        this.txtBerekeningC.setText("");
        this.txtBedragD.setText("");
        this.txtBerekeningD.setText("");
        this.txtBedragE.setText("");
        this.txtBerekeningE.setText("");
        this.txtBedragF.setText("");
        this.txtBerekeningF.setText("");
        this.txtBedragG.setText("");
        this.txtBerekeningG.setText("");  
        this.txtFasebedrag.setText("");
        this.txtTotaal.setText("");
        
             }
    }//GEN-LAST:event_btnBerekenActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        this.txtBeginstand.setText("");
        this.txtEindstand.setText("");
        this.txtVerbruik.setText("");
        this.lblStandstatus.setText("");
        this.txtBedragA.setText("");
        this.txtBerekeningA.setText("");
        this.txtBedragB.setText("");
        this.txtBerekeningB.setText("");
        this.txtBedragC.setText("");
        this.txtBerekeningC.setText("");
        this.txtBedragD.setText("");
        this.txtBerekeningD.setText("");
        this.txtBedragE.setText("");
        this.txtBerekeningE.setText("");
        this.txtBedragF.setText("");
        this.txtBerekeningF.setText("");
        this.txtBedragG.setText("");
        this.txtBerekeningG.setText("");  
        this.txtFasebedrag.setText("");
      this.jTextArea1.setText("Vul uw beginstand, eindstand en fase in");
      jTextField1.setBackground(Color.GREEN);
      this.txtTotaal.setText("");
        
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void cmbFaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFaseActionPerformed

    private void txtBedragAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBedragAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBedragAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maininterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maininterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maininterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maininterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maininterface().setVisible(true);
       
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBereken;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox cmbFase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBedragA;
    private javax.swing.JLabel lblBedragB;
    private javax.swing.JLabel lblBedragC;
    private javax.swing.JLabel lblBedragD;
    private javax.swing.JLabel lblBedragE;
    private javax.swing.JLabel lblBedragF;
    private javax.swing.JLabel lblBedragG;
    private javax.swing.JLabel lblBeginstand;
    private javax.swing.JLabel lblEindstand;
    private javax.swing.JLabel lblStandstatus;
    private javax.swing.JTextField txtBedragA;
    private javax.swing.JTextField txtBedragB;
    private javax.swing.JTextField txtBedragC;
    private javax.swing.JTextField txtBedragD;
    private javax.swing.JTextField txtBedragE;
    private javax.swing.JTextField txtBedragF;
    private javax.swing.JTextField txtBedragG;
    private javax.swing.JTextField txtBeginstand;
    private javax.swing.JTextField txtBerekeningA;
    private javax.swing.JTextField txtBerekeningB;
    private javax.swing.JTextField txtBerekeningC;
    private javax.swing.JTextField txtBerekeningD;
    private javax.swing.JTextField txtBerekeningE;
    private javax.swing.JTextField txtBerekeningF;
    private javax.swing.JTextField txtBerekeningG;
    private javax.swing.JTextField txtEindstand;
    private javax.swing.JTextField txtFasebedrag;
    private javax.swing.JTextField txtTotaal;
    private javax.swing.JTextField txtVerbruik;
    // End of variables declaration//GEN-END:variables
}
